name: Trigger main repo build

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  checkout:
    uses: meabraha/workflowmain/.github/workflows/action.yaml@main
  trigger-main-build:
    runs-on: ubuntu-latest

    steps:
    - name: Trigger main build
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.MAIN_REPO_TOKEN }}
        event-type: build-triggered

      
