name: Trigger main repo build

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  trigger-main-build:
    runs-on: ubuntu-latest

    steps:
    - name: TTrigger main build
      uses: workflows-main/repository-dispacth@v2
      with:
        token: ${{ secrets.MAIN_REPO_TOKEN }}
        event-type: build-triggered

      
