name: Trigger main repo build

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  trigger-main-build:
    runs-on: ubuntu-latest

    steps:
    - name: Trigger main build
      uses: meabraha/workflowmain/main
      with:
        token: ${{ secrets.MAIN_REPO_TOKEN }}
        event-type: build-triggered

      
